

DROP TABLE BASEDADOS;
DROP TABLE CPU;
DROP TABLE MEMORY;
DROP TABLE USERROLES;
DROP TABLE USERS_PRIVILEGESUSERS;
DROP TABLE USERS_PRIVILEGES;
DROP TABLE ROLES;
DROP TABLE SESSIONS;
DROP TABLE USERS;
DROP TABLE DATAFILES;
DROP TABLE TABLESPACES;
