

DROP TRIGGER CPU_Tr;
DROP TRIGGER Memory_Tr;
DROP TRIGGER SESSIONS_Tr;
DROP TRIGGER SESSION_Tr2;
DROP SEQUENCE CPU_Sq;
DROP SEQUENCE Memory_Sq;
DROP SEQUENCE Sessions_Sq;


DROP TABLE BASEDADOS;
DROP TABLE CPU;
DROP TABLE MEMORY;
DROP TABLE USERROLES;
DROP TABLE USER_PRIVILEGES;
DROP TABLE PRIVILEGES;
DROP TABLE ROLES;
DROP TABLE SESSIONS;
DROP TABLE USERS;
DROP TABLE DATAFILES;
DROP TABLE TABLESPACES;

