--TABLESPACE AEBD_TP
CREATE TABLESPACE AEBD_TP 
    DATAFILE 
        '\u01\app\oracle\oradata\orcl12\orcl\AEBD_TP_01.DBF' SIZE 500M;

--TABLESPACE TP_TEMP   
CREATE TEMPORARY TABLESPACE TP_TEMP 
    TEMPFILE 
        '\u01\app\oracle\oradata\orcl12\orcl\TP_TEMPORARY_01.DBF' SIZE 250M; 
    
--User

CREATE
USER grupo06
IDENTIFIED BY oracle
DEFAULT TABLESPACE AEBD_TP
TEMPORARY TABLESPACE TP_TEMP
QUOTA UNLIMITED on AEBD_TP;

GRANT CONNECT TO grupo06;
GRANT RESOURCE TO grupo06;
GRANT CREATE SESSION TO grupo06 ;
GRANT CREATE TABLE TO grupo06 ;
